modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/ServerI18nAPI/issues"
license = "MIT"

[[mods]]
modId = "server_i18n_api"
version = "${version}"
displayName = "Server I18n API"
authors = "IAFEnvoy"
description = '''
Server side standalone i18n system, for server side only mods.
'''
logoFile = "logo.png"

[[dependencies.server_i18n_api]]
modId = "neoforge"
type = "required"
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.server_i18n_api]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.21)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config="server_i18n_api.mixins.json"
